[toolchain]


[features]
seeds = false
skip-lint = false

[programs.localnet]
soda_unchained = "DJEXkPy4z1K9g8RvGUVqHy3EivJU64drXv3FvTJSJgbw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/tamur/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
