[toolchain]


[features]
seeds = false
skip-lint = false

[programs.localnet]
soda_unchained = "5cqC671u7TqttSQC3MBMTj41KkWC8pTebcg1kbXwP1hZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/tamur/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
